import type { Metadata } from "next";

import "./globals.css";
import CustomLayout from "./CustomLayout";

export const metadata: Metadata = {
  title: "딸기 마켓",
  description: "Generated by 유경환",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <CustomLayout> {children}</CustomLayout>
        </main>
      </body>
    </html>
  );
}
