import type { Metadata } from "next";

import "./globals.css";
import CustomLayout from "./CustomLayout";
import { AppProvider } from "@/contexts";

export const metadata: Metadata = {
  title: "딸기 마켓",
  description: "Generated by 유경환",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <CustomLayout> {children}</CustomLayout>
        </AppProvider>
      </body>
    </html>
  );
}
